/**
 * The piano arranger, ported from `llm-platform/piano-arrangement-lab`.
 *
 * Ported rather than pre-computed because the point of the demo is that you
 * can type any chords you like. A fixed set of baked arrangements would be a
 * gallery; this is the actual solver, running in the tab.
 *
 * `arranger.test.ts` checks this against a golden fixture generated by the
 * Python package — every voicing, every cost, every reported rule violation —
 * so the two cannot drift. Where the comments here are terse, the Python is
 * the place the reasoning is written down.
 */

export const MIDDLE_C = 60;

const LETTER_SEMITONES: Record<string, number> = {
  C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11,
};

const SHARP_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];

/** Semitones above the root for each chord quality. Mirrors `theory.QUALITIES`. */
export const QUALITIES: Record<string, number[]> = {
  "": [0, 4, 7], maj: [0, 4, 7], M: [0, 4, 7],
  m: [0, 3, 7], min: [0, 3, 7], "-": [0, 3, 7],
  dim: [0, 3, 6], o: [0, 3, 6], aug: [0, 4, 8], "+": [0, 4, 8],
  sus2: [0, 2, 7], sus4: [0, 5, 7], sus: [0, 5, 7],
  "7": [0, 4, 7, 10], maj7: [0, 4, 7, 11], M7: [0, 4, 7, 11],
  "Δ": [0, 4, 7, 11], "Δ7": [0, 4, 7, 11],
  m7: [0, 3, 7, 10], min7: [0, 3, 7, 10], "-7": [0, 3, 7, 10],
  mmaj7: [0, 3, 7, 11], mM7: [0, 3, 7, 11],
  dim7: [0, 3, 6, 9], o7: [0, 3, 6, 9],
  m7b5: [0, 3, 6, 10], "ø": [0, 3, 6, 10], "ø7": [0, 3, 6, 10],
  "7sus4": [0, 5, 7, 10], "7sus": [0, 5, 7, 10],
  "6": [0, 4, 7, 9], m6: [0, 3, 7, 9],
  aug7: [0, 4, 8, 10], "7#5": [0, 4, 8, 10], "7b5": [0, 4, 6, 10],
  "9": [0, 4, 7, 10, 14], maj9: [0, 4, 7, 11, 14], M9: [0, 4, 7, 11, 14],
  m9: [0, 3, 7, 10, 14],
  "11": [0, 4, 7, 10, 14, 17], m11: [0, 3, 7, 10, 14, 17],
  "13": [0, 4, 7, 10, 14, 21], maj13: [0, 4, 7, 11, 14, 21], m13: [0, 3, 7, 10, 14, 21],
  "7b9": [0, 4, 7, 10, 13], "7#9": [0, 4, 7, 10, 15],
  "7#11": [0, 4, 7, 10, 18], "7b13": [0, 4, 7, 10, 20],
  add9: [0, 4, 7, 14], madd9: [0, 3, 7, 14], "5": [0, 7],
};

const DEGREE_OF_INTERVAL: Record<number, string> = {
  0: "root", 2: "9th", 3: "3rd", 4: "3rd", 5: "11th", 6: "5th", 7: "5th",
  8: "5th", 9: "6th", 10: "7th", 11: "7th", 13: "9th", 14: "9th", 15: "9th",
  17: "11th", 18: "11th", 20: "13th", 21: "13th",
};

export class ChordError extends Error {}

export interface Chord {
  symbol: string;
  root: number;
  quality: string;
  intervals: number[];
  bass: number | null;
}

export function noteName(pitch: number): string {
  return `${SHARP_NAMES[((pitch % 12) + 12) % 12]}${Math.floor(pitch / 12) - 1}`;
}

/** Is a bass note specified that is not the root? */
export function isSlash(chord: Chord): boolean {
  return chord.bass !== null && chord.bass % 12 !== chord.root % 12;
}

/** Tones that may not be dropped: root, third (or sus fourth), seventh. */
function essentialIntervals(chord: Chord): number[] {
  const keep = new Set([0]);
  for (const interval of chord.intervals) {
    const degree = DEGREE_OF_INTERVAL[interval % 24] ?? "";
    if (degree === "3rd" || degree === "7th" ||
        (degree === "11th" && chord.quality.includes("sus"))) {
      keep.add(interval);
    }
  }
  return [...keep].sort((a, b) => a - b);
}

function parsePitchClass(letter: string, accidentals: string): number {
  const base = LETTER_SEMITONES[letter.toUpperCase()];
  const shift =
    [...accidentals].filter((c) => c === "#").length -
    [...accidentals].filter((c) => c === "b").length;
  return (((base + shift) % 12) + 12) % 12;
}

export function parseChord(symbol: string): Chord {
  let text = symbol.trim();
  if (!text) throw new ChordError("empty chord symbol");

  let bass: number | null = null;
  const slash = text.indexOf("/");
  if (slash !== -1) {
    const bassText = text.slice(slash + 1);
    text = text.slice(0, slash);
    const m = /^([A-Ga-g])([#b]*)\d*$/.exec(bassText.trim());
    if (!m) throw new ChordError(`not a bass note: ${bassText}`);
    bass = parsePitchClass(m[1], m[2]);
  }

  const rootMatch = /^([A-Ga-g])([#b]*)/.exec(text);
  if (!rootMatch) throw new ChordError(`no root note in ${symbol}`);
  const root = parsePitchClass(rootMatch[1], rootMatch[2]);
  const suffix = text.slice(rootMatch[0].length);

  // Longest match first, so "maj7" beats "maj" and "m7b5" beats "m7".
  const qualities = Object.keys(QUALITIES).sort((a, b) => b.length - a.length);
  for (const quality of qualities) {
    if (suffix === quality) {
      return { symbol: symbol.trim(), root, quality, intervals: QUALITIES[quality], bass };
    }
  }
  throw new ChordError(`unknown chord quality "${suffix}" in ${symbol}`);
}

export function parseProgression(text: string): Chord[] {
  const tokens = text.trim().split(/[\s|,]+/).filter(Boolean);
  if (tokens.length === 0) throw new ChordError("no chords found");
  return tokens.map(parseChord);
}

// --------------------------------------------------------------------------- //
// Difficulty
// --------------------------------------------------------------------------- //

export interface Level {
  name: string;
  maxSpan: number;
  maxRightNotes: number;
  maxLeftNotes: number;
  allowInversions: boolean;
  allowExtensions: boolean;
  rightLow: number;
  rightHigh: number;
  leftLow: number;
  leftHigh: number;
  motionWeight: number;
  ruleWeight: number;
  description: string;
}

export const LEVELS: Record<string, Level> = {
  beginner: {
    name: "beginner", maxSpan: 12, maxRightNotes: 3, maxLeftNotes: 1,
    allowInversions: false, allowExtensions: false,
    rightLow: MIDDLE_C, rightHigh: MIDDLE_C + 19,
    leftLow: MIDDLE_C - 24, leftHigh: MIDDLE_C - 5,
    motionWeight: 2.0, ruleWeight: 1.0,
    description:
      "Root-position chords only, a single bass note in the left hand, at most " +
      "three notes in the right, nothing wider than an octave, no extensions " +
      "and nothing outside the two octaves above middle C.",
  },
  intermediate: {
    name: "intermediate", maxSpan: 12, maxRightNotes: 4, maxLeftNotes: 2,
    allowInversions: true, allowExtensions: false,
    rightLow: MIDDLE_C - 4, rightHigh: MIDDLE_C + 21,
    leftLow: MIDDLE_C - 28, leftHigh: MIDDLE_C - 2,
    motionWeight: 1.0, ruleWeight: 1.0,
    description:
      "Sevenths and inversions are available, the left hand may play root and " +
      "fifth together, and the solver is free to invert chords to keep the " +
      "right hand still.",
  },
  advanced: {
    name: "advanced", maxSpan: 14, maxRightNotes: 5, maxLeftNotes: 3,
    allowInversions: true, allowExtensions: true,
    rightLow: MIDDLE_C - 7, rightHigh: MIDDLE_C + 26,
    leftLow: MIDDLE_C - 31, leftHigh: MIDDLE_C + 2,
    motionWeight: 0.5, ruleWeight: 0.6,
    description:
      "Extensions up to the 13th, tenths in the left hand, and a wider " +
      "register. Motion is cheap, so the solver will move a hand to reach a " +
      "richer voicing.",
  },
};

export interface Style {
  name: string;
  description: string;
  motionWeight: number;
  ruleWeight: number;
  prefersExtensions: boolean | null;
  fifthPenalty: number;
  extensionPenalty: number;
  targetDensity: number;
  densityWeight: number;
}

function style(
  name: string, description: string, over: Partial<Style> = {},
): Style {
  return {
    name, description,
    motionWeight: 1, ruleWeight: 1, prefersExtensions: null,
    fifthPenalty: 0.6, extensionPenalty: 0.3, targetDensity: 3, densityWeight: 0,
    ...over,
  };
}

export const STYLES: Record<string, Style> = {
  plain: style("plain", "Straight block chords, nothing added."),
  jazzy: style("jazzy",
    "Extensions where the level allows them, and the fifth dropped in favour " +
    "of colour tones — the shell voicing a jazz pianist reaches for.",
    { ruleWeight: 0.4, prefersExtensions: true, fifthPenalty: 0,
      extensionPenalty: 1.4, targetDensity: 4, densityWeight: 0.4 }),
  sparse: style("sparse",
    "As few notes as carry the harmony. Open, quiet, easy to play.",
    { fifthPenalty: 0, extensionPenalty: 0, targetDensity: 2,
      densityWeight: 0.9, motionWeight: 1.2 }),
  lush: style("lush",
    "Full, closely spaced chords with every available tone sounding.",
    { fifthPenalty: 1.2, extensionPenalty: 0.8, targetDensity: 5,
      densityWeight: 0.7, prefersExtensions: true }),
  hymn: style("hymn",
    "Four-part writing with strict voice leading and minimal motion — " +
    "parallel fifths are punished hard, as in a chorale.",
    { ruleWeight: 2.5, motionWeight: 1.6, fifthPenalty: 1.0,
      targetDensity: 3, densityWeight: 1.0 }),
};

/**
 * The level, adjusted by the style. Weights move; hard limits do not.
 *
 * A difficulty level is a promise about what the player's hands will be asked
 * to do. A style is a preference about sound. Letting the second override the
 * first would make the promise worthless.
 */
export function applyStyle(level: Level, s: Style): Level {
  return {
    ...level,
    motionWeight: level.motionWeight * s.motionWeight,
    ruleWeight: level.ruleWeight * s.ruleWeight,
    allowExtensions:
      s.prefersExtensions === null
        ? level.allowExtensions
        : level.allowExtensions && s.prefersExtensions,
  };
}

// --------------------------------------------------------------------------- //
// Voicings
// --------------------------------------------------------------------------- //

export const MAX_CANDIDATES = 60;
const BASS_LOW = 28;
const BASS_HIGH = 48;

export interface Voicing {
  left: number[];
  right: number[];
  chord: Chord;
  pitches: number[];
}

function makeVoicing(left: number[], right: number[], chord: Chord): Voicing {
  return { left, right, chord, pitches: [...left, ...right].sort((a, b) => a - b) };
}

export const spanOf = (notes: number[]): number =>
  notes.length > 1 ? notes[notes.length - 1] - notes[0] : 0;

export const voicingSpan = (v: Voicing): number =>
  Math.max(spanOf(v.right), spanOf(v.left));

export interface Simplified {
  chord: Chord;
  notes: string[];
}

/** Reduce a chord to what this level can play, reporting each reduction. */
export function simplify(chord: Chord, level: Level): Simplified {
  const notes: string[] = [];
  let intervals = chord.intervals;
  let bass = chord.bass;

  if (!level.allowExtensions) {
    const kept = intervals.filter((i) => {
      const d = DEGREE_OF_INTERVAL[i % 24];
      return d !== "9th" && d !== "11th" && d !== "13th";
    });
    if (kept.length !== intervals.length) {
      const dropped = [...new Set(
        intervals.filter((i) => !kept.includes(i))
          .map((i) => DEGREE_OF_INTERVAL[i % 24] ?? "?"),
      )].sort();
      notes.push(`dropped the ${dropped.join(", ")}`);
      intervals = kept;
    }
  }

  if (isSlash(chord) && !level.allowInversions) {
    notes.push("played in root position instead of over the written bass");
    bass = null;
  }

  if (notes.length === 0) return { chord, notes };
  return { chord: { ...chord, intervals, bass }, notes };
}

function pitchesIn(classes: Set<number>, low: number, high: number): number[] {
  const out: number[] = [];
  for (let p = low; p <= high; p++) if (classes.has(((p % 12) + 12) % 12)) out.push(p);
  return out;
}

export function staticCost(v: Voicing, level: Level, s: Style | null = null): number {
  let cost = 0;
  const comfortable = 9;
  for (const span of [spanOf(v.right), spanOf(v.left)]) {
    if (span > comfortable) cost += 0.8 * (span - comfortable);
  }

  const pitches = v.pitches;
  for (let i = 1; i < pitches.length; i++) {
    const a = pitches[i - 1];
    const b = pitches[i];
    if (b < 54 && b - a < 7) cost += (1.5 * (7 - (b - a))) / 7;
  }

  if (v.left.length && v.right.length) {
    const gap = Math.min(...v.right) - Math.max(...v.left);
    if (gap > 16) cost += 0.4 * (gap - 16);
  }

  const sounded = new Set(pitches.map((p) => ((p % 12) + 12) % 12));
  const fifthPenalty = s === null ? 0.6 : s.fifthPenalty;
  const colour = s === null ? 0.3 : s.extensionPenalty;
  for (const interval of v.chord.intervals) {
    const pc = (((v.chord.root + interval) % 12) + 12) % 12;
    if (sounded.has(pc)) continue;
    const degree = DEGREE_OF_INTERVAL[interval % 24] ?? "";
    if (degree === "5th") cost += fifthPenalty;
    else if (degree === "9th" || degree === "11th" || degree === "13th") cost += colour;
    else cost += 3.0;
  }

  const wantedBass = v.chord.bass ?? v.chord.root;
  const bass = pitches[0];
  if (((bass % 12) + 12) % 12 !== ((wantedBass % 12) + 12) % 12) {
    cost += isSlash(v.chord) ? 2.5 : 1.0;
  }

  cost += 0.15 * Math.max(0, pitches.length - 3);
  if (s !== null) cost += s.densityWeight * Math.abs(v.right.length - s.targetDensity);

  if (bass > BASS_HIGH) cost += 0.35 * (bass - BASS_HIGH);
  else if (bass < BASS_LOW) cost += 0.35 * (BASS_LOW - bass);

  const melody = pitches[pitches.length - 1];
  if (melody > level.rightHigh - 2) cost += 0.5 * (melody - (level.rightHigh - 2));
  return cost;
}

/** Every k-subset of `items`, in order. */
function combinations<T>(items: T[], k: number): T[][] {
  const out: T[][] = [];
  const pick = (start: number, chosen: T[]) => {
    if (chosen.length === k) { out.push([...chosen]); return; }
    for (let i = start; i < items.length; i++) {
      chosen.push(items[i]);
      pick(i + 1, chosen);
      chosen.pop();
    }
  };
  pick(0, []);
  return out;
}

export function candidates(chord: Chord, level: Level, s: Style | null = null): Voicing[] {
  const reduced = simplify(chord, level).chord;
  const pcs = new Set(
    reduced.intervals.map((i) => (((reduced.root + i) % 12) + 12) % 12),
  );
  const essential = new Set(
    essentialIntervals(reduced)
      .filter((i) => reduced.intervals.includes(i))
      .map((i) => (((reduced.root + i) % 12) + 12) % 12),
  );
  const bassPc = (((reduced.bass ?? reduced.root) % 12) + 12) % 12;

  const leftOptions: number[][] = [];
  for (const rootPitch of pitchesIn(new Set([bassPc]), level.leftLow, level.leftHigh)) {
    leftOptions.push([rootPitch]);
    const others = new Set([...pcs].filter((p) => p !== bassPc));
    if (level.maxLeftNotes >= 2) {
      for (const other of pitchesIn(others, rootPitch + 3, rootPitch + level.maxSpan)) {
        leftOptions.push([rootPitch, other]);
      }
    }
    if (level.maxLeftNotes >= 3) {
      const pool = pitchesIn(pcs, rootPitch + 3, rootPitch + level.maxSpan);
      for (const [a, b] of combinations(pool, 2)) leftOptions.push([rootPitch, a, b]);
    }
  }

  const rightPool = pitchesIn(pcs, level.rightLow, level.rightHigh);
  const rightOptions: number[][] = [];
  for (let size = 2; size <= level.maxRightNotes; size++) {
    for (const combo of combinations(rightPool, size)) {
      if (combo[combo.length - 1] - combo[0] > level.maxSpan) continue;
      const classes = new Set(combo.map((p) => ((p % 12) + 12) % 12));
      let complete = true;
      for (const pc of essential) if (!classes.has(pc)) { complete = false; break; }
      if (complete) rightOptions.push(combo);
    }
  }

  const out: Voicing[] = [];
  for (const left of leftOptions) {
    for (const right of rightOptions) {
      if (right[0] <= left[left.length - 1]) continue;
      out.push(makeVoicing(left, right, reduced));
    }
  }
  if (out.length === 0) {
    throw new ChordError(
      `${chord.symbol} cannot be voiced at the ${level.name} level`,
    );
  }
  out.sort((a, b) => staticCost(a, level, s) - staticCost(b, level, s));
  return out.slice(0, MAX_CANDIDATES);
}

// --------------------------------------------------------------------------- //
// Voice leading
// --------------------------------------------------------------------------- //

const PERFECT_FIFTH = 7;
const OCTAVE = 12;

export interface Violation {
  rule: string;
  detail: string;
  penalty: number;
}

export function explain(previous: Voicing, current: Voicing): Violation[] {
  const before = previous.pitches;
  const after = current.pitches;
  const n = Math.min(before.length, after.length);
  const found: Violation[] = [];

  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      const stepI = after[i] - before[i];
      const stepJ = after[j] - before[j];
      if (stepI === 0 || stepJ === 0 || stepI > 0 !== stepJ > 0) continue;
      const gapBefore = (((before[j] - before[i]) % OCTAVE) + OCTAVE) % OCTAVE;
      const gapAfter = (((after[j] - after[i]) % OCTAVE) + OCTAVE) % OCTAVE;
      if (gapBefore !== gapAfter) continue;
      const detail = `${before[i]}->${after[i]} against ${before[j]}->${after[j]}`;
      if (gapBefore === PERFECT_FIFTH) {
        found.push({ rule: "parallel fifths", detail, penalty: 4 });
      } else if (gapBefore === 0 && before[j] - before[i] >= OCTAVE) {
        found.push({ rule: "parallel octaves", detail, penalty: 4 });
      }
    }
  }

  for (let i = 0; i < n; i++) {
    const distance = Math.abs(after[i] - before[i]);
    const top = i === n - 1;
    const limit = top ? 12 : 9;
    if (distance > limit) {
      found.push({
        rule: "large leap",
        detail: `${top ? "melody" : `voice ${i + 1}`} moves ${distance} semitones`,
        penalty: 0.5 * (distance - limit),
      });
    }
  }

  for (let i = 1; i < n; i++) {
    if (after[i] < before[i - 1]) {
      found.push({
        rule: "voice overlap",
        detail: `voice ${i + 1} falls to ${after[i]}, below voice ${i}'s ${before[i - 1]}`,
        penalty: 1.5,
      });
    }
  }
  return found;
}

export function motion(previous: Voicing, current: Voicing): number {
  let distance = 0;
  if (previous.left.length && current.left.length) {
    distance += Math.abs(Math.min(...current.left) - Math.min(...previous.left));
  }
  if (previous.right.length && current.right.length) {
    distance += Math.abs(Math.min(...current.right) - Math.min(...previous.right));
  }
  return distance;
}

export function commonTones(previous: Voicing, current: Voicing): number {
  const held = new Set(previous.pitches);
  return current.pitches.filter((p) => held.has(p)).length;
}

export function transitionCost(previous: Voicing, current: Voicing, level: Level): number {
  let cost = level.ruleWeight * explain(previous, current)
    .reduce((total, v) => total + v.penalty, 0);
  cost += level.motionWeight * 0.25 * motion(previous, current);
  cost -= 0.3 * commonTones(previous, current);
  return cost;
}

// --------------------------------------------------------------------------- //
// The solver
// --------------------------------------------------------------------------- //

export interface Step {
  chord: Chord;
  voicing: Voicing;
  notes: string[];
  violations: Violation[];
  static: number;
  transition: number;
  cost: number;
}

export interface Arrangement {
  level: Level;
  style: Style;
  steps: Step[];
  totalCost: number;
  searched: number;
  totalMotion: number;
  maxSpan: number;
  simplifications: { symbol: string; note: string }[];
  violations: Violation[];
}

function summarise(level: Level, s: Style, steps: Step[], total: number, searched: number) {
  let totalMotion = 0;
  for (let i = 1; i < steps.length; i++) {
    totalMotion += motion(steps[i - 1].voicing, steps[i].voicing);
  }
  return {
    level, style: s, steps, totalCost: total, searched, totalMotion,
    maxSpan: steps.reduce((m, st) => Math.max(m, voicingSpan(st.voicing)), 0),
    simplifications: steps.flatMap((st) =>
      st.notes.map((note) => ({ symbol: st.chord.symbol, note })),
    ),
    violations: steps.flatMap((st) => st.violations),
  };
}

/**
 * Cheapest path through the lattice of candidate voicings.
 *
 * Viterbi: `best[i]` is the cost of the cheapest path ending at candidate `i`
 * of the current layer, `back[d][i]` the candidate in the previous layer it
 * came through. O(n·k²) against the kⁿ of trying every combination.
 */
export function arrange(
  input: string | Chord[],
  levelName = "intermediate",
  styleName = "plain",
): Arrangement {
  const chords = typeof input === "string" ? parseProgression(input) : input;
  if (chords.length === 0) throw new ChordError("no chords to arrange");
  const baseLevel = LEVELS[levelName];
  if (!baseLevel) throw new ChordError(`unknown level ${levelName}`);
  const s = STYLES[styleName];
  if (!s) throw new ChordError(`unknown style ${styleName}`);
  const level = applyStyle(baseLevel, s);

  const layers = chords.map((c) => candidates(c, level, s));
  const simplifications = chords.map((c) => simplify(c, level).notes);

  let best = layers[0].map((v) => staticCost(v, level, s));
  const back: number[][] = [];
  let searched = layers[0].length;

  for (let depth = 1; depth < layers.length; depth++) {
    const previousLayer = layers[depth - 1];
    const layer = layers[depth];
    const scores = new Array<number>(layer.length).fill(Infinity);
    const cameFrom = new Array<number>(layer.length).fill(0);
    for (let j = 0; j < layer.length; j++) {
      const own = staticCost(layer[j], level, s);
      for (let i = 0; i < previousLayer.length; i++) {
        const total = best[i] + own + transitionCost(previousLayer[i], layer[j], level);
        if (total < scores[j]) { scores[j] = total; cameFrom[j] = i; }
      }
    }
    searched += previousLayer.length * layer.length;
    best = scores;
    back.push(cameFrom);
  }

  let end = 0;
  for (let i = 1; i < best.length; i++) if (best[i] < best[end]) end = i;
  const total = best[end];
  const path = [end];
  for (let d = back.length - 1; d >= 0; d--) path.push(back[d][path[path.length - 1]]);
  path.reverse();

  const steps: Step[] = path.map((index, depth) => {
    const voicing = layers[depth][index];
    const previous = depth ? layers[depth - 1][path[depth - 1]] : null;
    const staticPart = staticCost(voicing, level, s);
    const transition = previous ? transitionCost(previous, voicing, level) : 0;
    return {
      chord: chords[depth],
      voicing,
      notes: simplifications[depth],
      violations: previous ? explain(previous, voicing) : [],
      static: staticPart,
      transition,
      cost: staticPart + transition,
    };
  });

  return summarise(level, s, steps, total, searched);
}

/** The obvious approach, kept so the solver can be measured against it. */
export function arrangeGreedy(
  input: string | Chord[],
  levelName = "intermediate",
  styleName = "plain",
): Arrangement {
  const chords = typeof input === "string" ? parseProgression(input) : input;
  const s = STYLES[styleName];
  const level = applyStyle(LEVELS[levelName], s);

  const steps: Step[] = [];
  let total = 0;
  let previous: Voicing | null = null;
  for (const chord of chords) {
    const layer = candidates(chord, level, s);
    let chosen = layer[0];
    let bestScore = Infinity;
    for (const v of layer) {
      const score = staticCost(v, level, s) +
        (previous ? transitionCost(previous, v, level) : 0);
      if (score < bestScore) { bestScore = score; chosen = v; }
    }
    const staticPart = staticCost(chosen, level, s);
    const transition = previous ? transitionCost(previous, chosen, level) : 0;
    total += staticPart + transition;
    steps.push({
      chord, voicing: chosen, notes: simplify(chord, level).notes,
      violations: previous ? explain(previous, chosen) : [],
      static: staticPart, transition, cost: staticPart + transition,
    });
    previous = chosen;
  }
  return summarise(level, s, steps, total, 0);
}

// --------------------------------------------------------------------------- //
// Reading a request without a model
// --------------------------------------------------------------------------- //

/**
 * The keyword parser, ported from `intent.parse_intent`.
 *
 * This is what makes the demo work for every visitor with no API key. It is
 * also why the page can honestly say what it did *not* understand: anything
 * left over after the known phrases are removed is reported rather than
 * quietly dropped.
 */
export interface Intent {
  level: string;
  style: string;
  bpm: number;
  beatsPerChord: number;
  unhandled: string;
}

const LEVEL_WORDS: Record<string, string[]> = {
  beginner: ["beginner", "easy", "easier", "simple", "simpler", "starter",
             "first year", "child", "kid", "novice", "basic"],
  intermediate: ["intermediate", "medium", "moderate", "normal", "standard"],
  advanced: ["advanced", "hard", "harder", "difficult", "virtuoso",
             "professional", "complex", "pro"],
};

const STYLE_WORDS: Record<string, string[]> = {
  jazzy: ["jazz", "jazzy", "bluesy", "swing", "smoky", "lounge"],
  sparse: ["sparse", "minimal", "quiet", "bare", "open", "spare", "thin",
           "gentle", "soft"],
  lush: ["lush", "rich", "full", "thick", "dense", "warm", "romantic", "cinematic"],
  hymn: ["hymn", "chorale", "church", "bach", "classical", "four part",
         "four-part", "sacred"],
  plain: ["plain", "simple chords", "block", "straight", "basic chords"],
};

const TEMPO_WORDS: Record<string, number> = {
  slow: 66, slower: 70, ballad: 68, relaxed: 76, calm: 72, sad: 66,
  mournful: 60, fast: 132, faster: 120, quick: 126, upbeat: 128,
  lively: 120, bright: 116, energetic: 138,
};

const STOPWORDS =
  /\b(make|it|a|an|the|please|can|you|i|want|would|like|to|be|more|less|and|but|with|sound|sounds|version|arrangement|play|this|that|my|of|in)\b/g;

const escape = (word: string) => word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function parseIntent(text: string, base?: Partial<Intent>): Intent {
  const intent: Intent = {
    level: "intermediate", style: "plain", bpm: 90, beatsPerChord: 2,
    unhandled: "", ...base,
  };
  const lowered = ` ${text.toLowerCase()} `;
  const consumed: string[] = [];

  /** The category whose phrase appears latest in the sentence wins. */
  const lastMatch = (table: Record<string, string[]>): string | null => {
    let best: [string, number] | null = null;
    for (const [key, words] of Object.entries(table)) {
      for (const word of words) {
        const pattern = new RegExp(`\\b${escape(word)}\\b`, "g");
        let found: RegExpExecArray | null;
        while ((found = pattern.exec(lowered)) !== null) {
          consumed.push(word);
          if (best === null || found.index > best[1]) best = [key, found.index];
        }
      }
    }
    return best?.[0] ?? null;
  };

  const level = lastMatch(LEVEL_WORDS);
  if (level) intent.level = level;
  const style = lastMatch(STYLE_WORDS);
  if (style) intent.style = style;
  const tempo = lastMatch(
    Object.fromEntries(Object.keys(TEMPO_WORDS).map((w) => [w, [w]])),
  );
  if (tempo) intent.bpm = TEMPO_WORDS[tempo];

  const explicit = /\b(\d{2,3})\s*(?:bpm|beats per minute)\b/.exec(lowered);
  if (explicit) {
    intent.bpm = Number(explicit[1]);
    consumed.push(explicit[0]);
  }

  let leftover = lowered;
  for (const word of consumed) leftover = leftover.split(word).join(" ");
  leftover = leftover.replace(STOPWORDS, " ");
  intent.unhandled = leftover.split(/\s+/).filter(Boolean).join(" ");
  return intent;
}

// --------------------------------------------------------------------------- //
// MIDI
// --------------------------------------------------------------------------- //

const TICKS_PER_BEAT = 480;

/** MIDI's 7-bits-per-byte integer, high bit set on all but the last. */
function variableLength(value: number): number[] {
  const out = [value & 0x7f];
  let rest = value >> 7;
  while (rest > 0) {
    out.push((rest & 0x7f) | 0x80);
    rest >>= 7;
  }
  return out.reverse();
}

function track(events: number[]): number[] {
  const body = [...events, 0x00, 0xff, 0x2f, 0x00];
  const size = body.length;
  return [
    0x4d, 0x54, 0x72, 0x6b,
    (size >> 24) & 0xff, (size >> 16) & 0xff, (size >> 8) & 0xff, size & 0xff,
    ...body,
  ];
}

function handTrack(chords: number[][], ticks: number, velocity: number): number[] {
  const events: number[] = [];
  let pending = 0;
  for (const pitches of chords) {
    if (pitches.length === 0) { pending += ticks; continue; }
    pitches.forEach((pitch, i) => {
      events.push(...variableLength(i === 0 ? pending : 0), 0x90, pitch, velocity);
    });
    pending = 0;
    pitches.forEach((pitch, i) => {
      events.push(...variableLength(i === 0 ? ticks : 0), 0x80, pitch, 0);
    });
  }
  return track(events);
}

/**
 * A two-track Standard MIDI File, left hand and right hand.
 *
 * The header chunk carries its own four-byte length before its six bytes of
 * data. The Python writer originally omitted it and produced a file of exactly
 * the right size that no parser would open, which is why the test for this
 * parses its output back rather than checking it is non-empty.
 */
export function toMidi(a: Arrangement, bpm = 90, beatsPerChord = 2): Uint8Array<ArrayBuffer> {
  const ticks = Math.round(beatsPerChord * TICKS_PER_BEAT);
  const microseconds = Math.round(60_000_000 / bpm);
  const header = [
    0x4d, 0x54, 0x68, 0x64, 0x00, 0x00, 0x00, 0x06,
    0x00, 0x01, 0x00, 0x03,
    (TICKS_PER_BEAT >> 8) & 0xff, TICKS_PER_BEAT & 0xff,
  ];
  const tempo = track([
    0x00, 0xff, 0x51, 0x03,
    (microseconds >> 16) & 0xff, (microseconds >> 8) & 0xff, microseconds & 0xff,
  ]);
  const bytes = [
    ...header,
    ...tempo,
    ...handTrack(a.steps.map((s) => s.voicing.left), ticks, 70),
    ...handTrack(a.steps.map((s) => s.voicing.right), ticks, 85),
  ];
  // Allocated against an explicit ArrayBuffer so the result is a `BlobPart`;
  // a bare `new Uint8Array(numbers)` is typed over `ArrayBufferLike`, which
  // could be shared memory and which `Blob` will not accept.
  const out = new Uint8Array(new ArrayBuffer(bytes.length));
  out.set(bytes);
  return out;
}
