/**
 * Cross-checks every TypeScript port against golden fixtures generated by the
 * Python projects (`site/scripts/generate_demo_data.py`).
 *
 * The demos re-implement logic that already exists in Python, which risks the
 * two quietly disagreeing. These tests make a divergence a failure.
 */

import { describe, expect, it } from "vitest";

import cardsGolden from "../../data/demos/cards-golden.json";
import coursesGolden from "../../data/demos/courses-golden.json";
import coursesData from "../../data/demos/courses.json";
import factorGolden from "../../data/demos/factor-golden.json";
import prices from "../../data/demos/factor-prices.json";
import trieGolden from "../../data/demos/trie-golden.json";

import { type Card, type Rank, type Suit, HAND_SCORES, scoreCards } from "./cards";
import { type FactorName, performanceMetrics, runBacktest, zscore } from "./factor";
import { LruCache } from "./lru";
import { type Course, coursesConflict, meetingsOverlap, searchByCode } from "./schedule";
import { Trie, characterToKey } from "./trie";

// --------------------------------------------------------------------------- //
// Trie
// --------------------------------------------------------------------------- //

describe("trie", () => {
  const trie = new Trie(
    Object.fromEntries(trieGolden.words.map((w) => [w, `https://example.com/${w}`])),
  );

  it("matches the Python on every prefix query", () => {
    for (const [query, expected] of Object.entries(trieGolden.prefix)) {
      expect([...trie.keysWithPrefix(query)].sort()).toEqual(expected);
    }
  });

  it("matches the Python on every wildcard query", () => {
    for (const [query, expected] of Object.entries(trieGolden.wildcard)) {
      const got = [...trie.wildcardSearch(query)].map(([k]) => k).sort();
      expect(got).toEqual(expected);
    }
  });

  it("holds every word", () => {
    expect(trie.size).toBe(trieGolden.words.length);
    expect([...trie.keys()].sort()).toEqual([...trieGolden.words].sort());
  });

  it("folds letters case-insensitively and everything else into one bucket", () => {
    expect(characterToKey("a")).toBe(0);
    expect(characterToKey("A")).toBe(0);
    expect(characterToKey("z")).toBe(25);
    for (const c of ["1", " ", "-", "'"]) expect(characterToKey(c)).toBe(26);
  });

  it("rejects a multi-character input", () => {
    expect(() => characterToKey("ab")).toThrow();
  });

  it("does not treat a prefix of a key as a key", () => {
    expect(trie.has("par")).toBe(false);
    expect(trie.has("park")).toBe(true);
  });

  it("reports the walked path for the visualisation", () => {
    expect(trie.pathFor("par")).toHaveLength(4); // root + p + a + r
    expect(trie.pathFor("zzz")).toHaveLength(1); // root only
  });
});

// --------------------------------------------------------------------------- //
// Card scoring
// --------------------------------------------------------------------------- //

describe("card scoring", () => {
  it("matches the Python on all 400 golden hands", () => {
    let checked = 0;
    for (const testCase of cardsGolden.cases) {
      const hand = testCase.hand.map((c) => ({
        suit: c.suit as Suit,
        rank: c.rank as Rank,
      }));
      expect(scoreCards(hand)).toBe(testCase.rank);
      checked += 1;
    }
    expect(checked).toBe(400);
  });

  it("agrees with the Python point table", () => {
    for (const testCase of cardsGolden.cases.slice(0, 50)) {
      expect(HAND_SCORES[scoreCards(
        testCase.hand.map((c) => ({ suit: c.suit as Suit, rank: c.rank as Rank })),
      )]).toBe(testCase.points);
    }
  });

  const hand = (...specs: string[]): Card[] => {
    const suits: Record<string, Suit> = {
      C: "clubs", D: "diamonds", H: "hearts", S: "spades",
    };
    return specs.map((s) => ({
      suit: suits[s.slice(-1)],
      rank: s.slice(0, -1) as Rank,
    }));
  };

  it("scores a six-card flush, which the original missed", () => {
    expect(scoreCards(hand("2H", "4H", "6H", "8H", "10H", "QH", "3S"))).toBe("Flush");
  });

  it("scores two triples as a full house, which the original missed", () => {
    expect(scoreCards(hand("2H", "2S", "2C", "5H", "5S", "5C", "9D"))).toBe("FullHouse");
  });

  it("scores an empty hand as nothing", () => {
    expect(scoreCards([])).toBe("None");
  });
});

// --------------------------------------------------------------------------- //
// Schedule conflicts
// --------------------------------------------------------------------------- //

describe("schedule", () => {
  const courses = coursesData.courses as Course[];
  const byCode = new Map(courses.map((c) => [c.code, c]));

  it("matches the Python on every course pair", () => {
    expect(coursesGolden.pairs.length).toBeGreaterThan(300);
    for (const pair of coursesGolden.pairs) {
      const a = byCode.get(pair.a)!;
      const b = byCode.get(pair.b)!;
      expect(coursesConflict(a, b)).toBe(pair.conflicts);
    }
  });

  it("treats back-to-back meetings as compatible", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1080, end: 1170 }, { day: 0, start: 1170, end: 1260 }),
    ).toBe(false);
  });

  it("treats overlapping meetings on the same day as a conflict", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1050, end: 1230 }, { day: 0, start: 1080, end: 1170 }),
    ).toBe(true);
  });

  it("ignores the same hours on different days", () => {
    expect(
      meetingsOverlap({ day: 0, start: 1080, end: 1170 }, { day: 1, start: 1080, end: 1170 }),
    ).toBe(false);
  });

  it("searches by prefix, not substring", () => {
    const hits = searchByCode(courses, "530");
    expect(hits.length).toBeGreaterThan(0);
    for (const c of hits) expect(c.code.split(" ")[1].startsWith("530")).toBe(true);
    // "112" sits inside "MPCS 53112-1" but is not a prefix of the number.
    expect(searchByCode(courses, "112")).toEqual([]);
  });
});

// --------------------------------------------------------------------------- //
// Factor backtest
// --------------------------------------------------------------------------- //

describe("factor backtest", () => {
  it("reproduces every golden case from the Python", () => {
    for (const expected of factorGolden.cases) {
      const result = runBacktest(prices, {
        factors: expected.factors as FactorName[],
        topN: expected.top_n,
        rebalanceEvery: expected.rebalance_every,
        initialCash: factorGolden.initial_cash,
      });
      const metrics = performanceMetrics(result.nav);

      expect(result.rebalanceCount).toBe(expected.rebalances);
      // Floating-point accumulation differs slightly across languages.
      expect(metrics.totalReturn).toBeCloseTo(expected.total_return, 4);
      expect(metrics.sharpeRatio).toBeCloseTo(expected.sharpe_ratio, 3);
      expect(metrics.maxDrawdown).toBeCloseTo(expected.max_drawdown, 4);
    }
  });

  it("tracks the Python's NAV path, not just its endpoints", () => {
    const expected = factorGolden.cases[0];
    const result = runBacktest(prices, {
      factors: expected.factors as FactorName[],
      topN: expected.top_n,
      rebalanceEvery: expected.rebalance_every,
      initialCash: factorGolden.initial_cash,
    });
    const sampled = result.nav.filter((_, i) => i % 50 === 0);
    expect(sampled).toHaveLength(expected.nav_samples.length);
    sampled.forEach((value, i) => {
      expect(value).toBeCloseTo(expected.nav_samples[i], 2);
    });
  });

  it("starts at the initial cash", () => {
    const result = runBacktest(prices, {
      factors: ["momentum"], topN: 3, rebalanceEvery: 21, initialCash: 100000,
    });
    expect(result.nav[0]).toBeCloseTo(100000, 6);
  });

  it("look-ahead mode beats the honest backtest on this universe", () => {
    const options = {
      factors: ["momentum"] as FactorName[],
      topN: 2, rebalanceEvery: 21, initialCash: 100000,
    };
    const honest = performanceMetrics(runBacktest(prices, options).nav);
    const cheating = performanceMetrics(
      runBacktest(prices, { ...options, lookAhead: true }).nav,
    );
    // The whole point of the demo: seeing the future pays.
    expect(cheating.totalReturn).toBeGreaterThan(honest.totalReturn);
  });

  it("z-scores a flat cross-section to zero rather than NaN", () => {
    const flat = zscore(new Map([["a", 5], ["b", 5]]));
    expect([...flat.values()]).toEqual([0, 0]);
  });

  it("rejects a NAV series too short to measure", () => {
    expect(() => performanceMetrics([100])).toThrow();
  });
});

// --------------------------------------------------------------------------- //
// LRU
// --------------------------------------------------------------------------- //

describe("lru cache", () => {
  const identity = (k: string) => k;

  it("evicts the least recently used key", () => {
    const cache = new LruCache(3);
    for (const k of ["a", "b", "c"]) cache.call(k, identity);
    const event = cache.call("d", identity);
    expect(event.evicted).toBe("a");
    expect(cache.order).toEqual(["b", "c", "d"]);
  });

  it("a hit protects a key from the next eviction", () => {
    const cache = new LruCache(3);
    for (const k of ["a", "b", "c"]) cache.call(k, identity);
    cache.call("a", identity);
    expect(cache.call("d", identity).evicted).toBe("b");
  });

  it("counts hits and misses", () => {
    const cache = new LruCache(10);
    cache.call("a", identity);
    cache.call("a", identity);
    expect([cache.hits, cache.misses]).toEqual([1, 1]);
    expect(cache.hitRate).toBeCloseTo(0.5);
  });

  it("never exceeds its size", () => {
    const cache = new LruCache(4);
    for (let i = 0; i < 50; i++) cache.call(String(i), identity);
    expect(cache.size).toBe(4);
  });

  it("caches nothing at size zero but still counts", () => {
    const cache = new LruCache(0);
    cache.call("a", identity);
    cache.call("a", identity);
    expect(cache.misses).toBe(2);
    expect(cache.size).toBe(0);
  });

  it("reports a zero hit rate before any call", () => {
    expect(new LruCache(4).hitRate).toBe(0);
  });
});
