/**
 * Port of `trie_search.trie` (Python) for the browser demo.
 *
 * Kept deliberately close to the original so the two can be compared line by
 * line. `trie.test.ts` checks it against golden fixtures generated by the
 * Python, so a divergence fails a test rather than quietly disagreeing.
 */

export const ALPHABET_SIZE = 26;
export const OTHER = 26;
export const WILDCARD = "?";

const CODE_A = "a".charCodeAt(0);

/** Map a character to [0, 26]. Letters go to 0-25; anything else to 26. */
export function characterToKey(char: string): number {
  if ([...char].length !== 1) {
    throw new Error(`expected a single character, got ${JSON.stringify(char)}`);
  }
  const lowered = char.toLowerCase();
  if (lowered >= "a" && lowered <= "z") return lowered.charCodeAt(0) - CODE_A;
  return OTHER;
}

function indexToChar(index: number): string {
  return index < ALPHABET_SIZE ? String.fromCharCode(index + CODE_A) : "_";
}

export class TrieNode {
  children = new Map<number, TrieNode>();
  isTerminal = false;
  /** The key text as first inserted, so the lossy folding is recoverable. */
  key: string | null = null;
  value: unknown = null;
}

export class Trie {
  readonly root = new TrieNode();
  private count = 0;

  constructor(entries?: Record<string, unknown>) {
    for (const [key, value] of Object.entries(entries ?? {})) this.set(key, value);
  }

  get size(): number {
    return this.count;
  }

  private find(key: string): TrieNode | null {
    let node: TrieNode | undefined = this.root;
    for (const char of key) {
      node = node.children.get(characterToKey(char));
      if (!node) return null;
    }
    return node ?? null;
  }

  set(key: string, value: unknown): void {
    let node = this.root;
    for (const char of key) {
      const index = characterToKey(char);
      let child = node.children.get(index);
      if (!child) {
        child = new TrieNode();
        node.children.set(index, child);
      }
      node = child;
    }
    if (!node.isTerminal) {
      node.isTerminal = true;
      node.key = key;
      this.count += 1;
    }
    node.value = value;
  }

  get(key: string): unknown {
    const node = this.find(key);
    return node?.isTerminal ? node.value : undefined;
  }

  has(key: string): boolean {
    return this.find(key)?.isTerminal ?? false;
  }

  /** Every key, in alphabetical order, in the folded alphabet. */
  *keys(): Generator<string> {
    yield* this.walk(this.root, "");
  }

  private *walk(node: TrieNode, prefix: string): Generator<string> {
    if (node.isTerminal) yield prefix;
    for (const index of [...node.children.keys()].sort((a, b) => a - b)) {
      yield* this.walk(node.children.get(index)!, prefix + indexToChar(index));
    }
  }

  /** Every key beginning with `prefix`. This is what a trie is for. */
  *keysWithPrefix(prefix: string): Generator<string> {
    const node = this.find(prefix);
    if (!node) return;
    const folded = [...prefix].map((c) => indexToChar(characterToKey(c))).join("");
    yield* this.walk(node, folded);
  }

  /** Search with `?` standing for exactly one character. */
  *wildcardSearch(pattern: string): Generator<[string, unknown]> {
    yield* this.match(this.root, "", pattern);
  }

  private *match(
    node: TrieNode,
    prefix: string,
    pattern: string,
  ): Generator<[string, unknown]> {
    if (pattern.length === 0) {
      if (node.isTerminal) yield [prefix, node.value];
      return;
    }
    const char = pattern[0];
    const rest = pattern.slice(1);

    if (char === WILDCARD) {
      for (const index of [...node.children.keys()].sort((a, b) => a - b)) {
        yield* this.match(node.children.get(index)!, prefix + indexToChar(index), rest);
      }
      return;
    }
    const index = characterToKey(char);
    const child = node.children.get(index);
    if (child) yield* this.match(child, prefix + indexToChar(index), rest);
  }

  /** Nodes on the path a key or pattern walks. Drives the visualisation. */
  pathFor(prefix: string): TrieNode[] {
    const path: TrieNode[] = [this.root];
    let node: TrieNode | undefined = this.root;
    for (const char of prefix) {
      node = node.children.get(characterToKey(char));
      if (!node) break;
      path.push(node);
    }
    return path;
  }
}
