/**
 * Cross-checks the TypeScript trend port against the Python that produced the
 * bundled data.
 *
 * `nb-weather.json` is generated by `scripts/generate_weather_results.py`,
 * which imports `climate_trend` — so the file is a golden fixture recording
 * what the reference implementation says about six real 75-year records. If
 * `trend.ts` disagrees with it, a city the visitor searches for would be
 * analysed differently from a city that shipped with the site, and nothing on
 * screen would reveal it.
 *
 * The tolerances are tight on purpose. These are the same arithmetic, not two
 * approximations of it; the only slack needed is for the JSON being rounded to
 * four decimals and for the t-distribution being evaluated by a different
 * routine here than in SciPy.
 */

import { describe, expect, it } from "vitest";

import weather from "../data/demos/nb-weather.json";
import {
  mannKendall,
  neweyWest,
  ordinaryLeastSquares,
  residualAutocorrelation,
} from "./trend";

const CITIES = Object.entries(weather.cities);

describe("the trend port", () => {
  it("has cities to check", () => {
    expect(CITIES.length).toBeGreaterThan(0);
  });

  for (const [name, city] of CITIES) {
    describe(name, () => {
      const years = city.annual.map((a) => a.year);
      const temps = city.annual.map((a) => a.temp);

      it("matches the Python OLS slope and interval", () => {
        const ours = ordinaryLeastSquares(years, temps);
        const theirs = city.trends.ols;
        expect(ours.slope).toBeCloseTo(theirs.slope, 4);
        expect(ours.standardError!).toBeCloseTo(theirs.se!, 4);
        expect(ours.low).toBeCloseTo(theirs.low, 4);
        expect(ours.high).toBeCloseTo(theirs.high, 4);
        expect(ours.pValue).toBeCloseTo(theirs.p, 5);
      });

      it("matches the Python Newey-West standard error", () => {
        const ours = neweyWest(years, temps);
        const theirs = city.trends.newey_west;
        expect(ours.method).toBe(theirs.method);
        expect(ours.slope).toBeCloseTo(theirs.slope, 4);
        expect(ours.standardError!).toBeCloseTo(theirs.se!, 4);
        expect(ours.low).toBeCloseTo(theirs.low, 4);
        expect(ours.high).toBeCloseTo(theirs.high, 4);
      });

      it("widens the interval rather than narrowing it", () => {
        // The whole reason the correction is here. Positively autocorrelated
        // residuals mean the naive interval is too confident, never too shy.
        const ols = ordinaryLeastSquares(years, temps);
        const hac = neweyWest(years, temps);
        expect(hac.width).toBeGreaterThan(ols.width);
        expect(hac.width / ols.width).toBeCloseTo(city.interval_inflation, 2);
      });

      it("matches the Python Mann-Kendall result", () => {
        const ours = mannKendall(years, temps);
        const theirs = city.trends.mann_kendall;
        expect(ours.slope).toBeCloseTo(theirs.slope, 4);
        expect(ours.low).toBeCloseTo(theirs.low, 4);
        expect(ours.high).toBeCloseTo(theirs.high, 4);
        // Both are far below any threshold; compare on a log scale so a
        // p-value of 1e-10 is not judged against an absolute tolerance.
        expect(ours.pValue).toBeLessThan(0.05);
        expect(theirs.p).toBeLessThan(0.05);
      });

      it("reports no standard error for the rank test", () => {
        expect(mannKendall(years, temps).standardError).toBeNull();
        expect(city.trends.mann_kendall.se).toBeNull();
      });

      it("matches the Python autocorrelation diagnostics", () => {
        const ours = residualAutocorrelation(years, temps);
        const theirs = city.autocorrelation;
        expect(ours.lag1).toBeCloseTo(theirs.lag1, 4);
        expect(ours.durbinWatson).toBeCloseTo(theirs.durbin_watson, 3);
        expect(ours.effectiveSampleSize).toBeCloseTo(theirs.effective_n, 1);
        expect(ours.n).toBe(theirs.n);
        expect(ours.correlated).toBe(theirs.correlated);
        expect(ours.inflation).toBeCloseTo(theirs.inflation, 2);
      });
    });
  }
});
